resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example
      
pipelines:
  - name: nexploitrepeater
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: jfrognexploit
        execution:
          onStart:
            - echo "Preparing for work..."
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update            
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install -y nodejs
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
          onExecute:
            - |
              printf "Start Repeater 🏁"
              PID_REPEATER=$(nexploit-cli repeater --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r --id pQVpFx4swaytVDV9m5p3fS &> /dev/null & echo $!)
              printf "Repeater started PID: $PID_REPEATER"
              sleep 10
              printf "Start NeuraLegion Scan 🏁"
              SCAN_ID=$(nexploit-cli scan:run --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r --repeater pQVpFx4swaytVDV9m5p3fS --name "JFrog scan with repeater" --crawler https://brokencrystals.com/ --smart)
              printf "Scan was started with ID https://app.neuralegion.com/scans/$SCAN_ID"
              sleep 10
              printf "Wait for issues ⏳"
            - | 
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r $SCAN_ID
