resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: nexploitIntegration
      path: nerkote/jfrog-example

pipelines:
  - name: nexploit_repeater
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: NEXPLOIT
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt -y update
            - apt-get -y install apt-transport-https ca-certificates curl software-properties-common
            - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            - curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            - chmod +x ~/docker-compose
            - mv ~/docker-compose /usr/local/bin/docker-compose
            - setup_remote_docker
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - pt-get -y install libnode-dev node-gyp libssl-dev
            - sudo apt-get install -y nodejs
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - docker-compose --env-file=.env up -d
            - docker-compose config
            - |
              SCAN_ID=$(nexploit-cli scan:run                
                --token vs0gxzp.nexa.vqnc7olwz03nwemiobr4oiluhgfgcg0m                         \
                  --name "💎 Broken Crystals for Jfrog repeater" \
                --repeater 4rTdvf9AUoqY9SnXSiXQTU                                            \
                --crawler https://brokencrystals.com                                        \
                --smart)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token vs0gxzp.nexa.vqnc7olwz03nwemiobr4oiluhgfgcg0m  \
                --breakpoint medium_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token vs0gxzp.nexa.vqnc7olwz03nwemiobr4oiluhgfgcg0m $SCAN_ID
